export enum Screen {
  SIGN_IN,
  SIGN_UP,
  MAIN_MENU,
  DRIVING_START_ALCOHOL,
  DRIVING_START_FUEL,
  DRIVING_START_MILEAGE,
  REFUEL_METER,
  REFUEL_RECEIPT,
  REFUEL_CONFIRM,
  REFUEL_COMPLETE,
  ETC_START,
  ETC_IN_USE,
  ETC_ARRIVED,
  RESERVE,
  RESERVE_SCHEDULE,
  DRIVING_LOG,
  MILEAGE_CONFIRM
}

export enum EtcStep {
  START = 'START',
  IN_USE = 'IN_USE',
  ARRIVED = 'ARRIVED'
}
